### ISSUE TITLE
integration: provide bundle

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-uikit#120]
Like for LaxarJS Patterns, there should be a dist-repository for LaxarJS UiKit named `dist-laxar-uikit`.
For the bower-registry, we should add the dist package as an artifact `laxar-uikit`.

**Comment by alex3683** [comment]
Added the dist bundle as `laxar-uikit` to the bower registry. The repository can be found at https://github.com/LaxarJS/dist-laxar-uikit.
