### ISSUE TITLE
remove dom-helper for prefix test

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-uikit#139]
In modern browsers, the dom-helper for determining the CSS transform prefix should no longer be needed. If a project needs this, it should use a dedicated solution (outside of the laxarjs scope).

**Comment by x1B** [comment]
The number of browsers supporting only the prefixed version is dwindling:
http://caniuse.com/#search=transform

**Comment by x1B** [comment]
Here is a good alternative for clients that depend on this: https://davidwalsh.name/vendor-prefix

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

### BREAKING CHANGE

The helper method `dom.cssTransformPropertyName` has been removed as highly specific to a narrow set of use cases, and as it is no longer needed when using modern Browsers (http://caniuse.com/#search=transform), or library abstractions such as `ng.$animate`.

Even if this functionality is needed, there are now better ways to calculate prefixes, that also cover other CSS properties: https://davidwalsh.name/vendor-prefix

**Comment by jpommerening** [comment]
@x1B https://github.com/LaxarJS/laxar-uikit/blob/b94e425/laxar-uikit.js#L6

**Comment by x1B** [comment]
@jpommerening 🍰
