### ISSUE TITLE
Instructions unclear. Travis broken ☠️

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar-uikit#143]
Currently, tests on master fail because:

```
ERROR in ./lib/spec/i18n_spec.js
Module not found: Error: Cannot resolve module 'laxar/lib/testing/i18n_mock' in /Users/jpommerening/Developer/github.com/shop-demo/includes/lib/laxar-uikit/lib/spec
 @ ./lib/spec/i18n_spec.js 3:17-55
```

This seems to relate to LaxarJS/laxar#351 and/or LaxarJS/laxar#350.
However, I'm not exactly sure what the proposed solution is. Also neither of those issues are "breaking".

**Comment by x1B** [comment]
The tests should never have directly loaded an internal laxar module, but previously there was no other way. Now we should be able to use the documented entry point for widget-services.

**Comment by x1B** [comment]
### BREAKING CHANGE

The method `i18n.languageTagFromScope( $scope )` has been removed as it only applies to AngularJS v1. Any clients that are currently using this functionality should instead use this snippet:

```javascript
var i18n = $scope.$eval( "i18n" );
var languageTag = i18n.tags[ i18n.locale ] || 'en';
```
