### ISSUE TITLE
Add proper README.md with setup instructions.

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar-uikit#144]
As mentioned in #142, there are no setup instructions and general information about this repo.

We should add enough docs to help users:

- Use Laxar-UIKit from JS
- Use the Laxar-UIKit default.theme (or at least mention that *this* is where the default.theme *is*)
- Create their own theme with Sass and `@import`s from Laxar-UIKit

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

Added lots of meat to the README.md, and added a link to the LaxarJS manual on themes.
