### ISSUE TITLE
Accept Date objects as input for date formatter

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar-uikit#157]
When using the date formatter, the user has to supply a date string for no other reason than `laxar-uikit` asserting the string type. This can lead to some unnecessary and error-prone back-and-forth conversion (#156). Since the current implementation uses `moment`, which accepts Date objects, I don't see any reason why we should enforce strings, especially since it is way to easy to get into timezone problems with that.

I think this could safely be implemented in both v1 and v2, but correct me (and the issue labels) if I'm wrong.

**Comment by x1B** [comment]
@jpommerening while we're at it: in addition to `Date` we should always prefer to accept full ISO-Datetime strings (over the TZ-error-prone date OR time fragments).

**Comment by x1B** [comment]
Since it's an enhancement, I am only solving this for `v2.x` for now.
If projects on `v1.x` are in dire need of this feature, please create a new issue.

**Comment by x1B** [comment]
### Upgrade Information

The date and time formatters (and their i18n-aware variants) now also accept JavaScript `Date` objects and full ISO-datetime strings, in addition to `"NOW"` and date-only/time-only strings.

- The date-only string should be used as input when no time portion is available (e.g. for a holiday), while the full input should be used when rendering "just the date" portion of a full datetime (e.g. "last modified at $date").

- Conversely, the time-only input should be used for "time-of-day" style data ("every day at $time"), while the full input should be used to display "just the time" of a full datetime (e.g. "Log message at $time: …").

This usage should ensure that the local time of the user is respected whenever that is appropriate.

**Comment by jpommerening** [comment]
That was quick :clap:

**Comment by x1B** [comment]
@jpommerening I may have needed this 😬
