### ISSUE TITLE
axInput: Possible timing problem when entering invalid input

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-uikit#89]
Scenario:
Input-Field with following ax-input* directives:
```
data-ng-model-options="{ debounce: 300 }"
data-ax-input="integer"
data-ax-input-required="true"
data-ax-input-minimum-value="0"
```
and valid initial model value of e.g. 20000.

Reproduction steps:
1. select complete content of the field
2. press delete or backspace
3. instantly click somewhere else (i.e. steal focus)

Result:
The 20000 reappears and the field is marked as invalid. When focussing the field again, the field is automatically emptied and the error tooltip is shown.

Expected:
The 20000 should not reappear after focus is lost in the field.

---

Possible reason:
The cause is most probably the focusout behavior of ax-input: In case the input loses focus, a previously removed grouping separator is inserted again by rendering the current, valid model value. Due to `data-ng-model-options="{ debounce: 300 }"` this may still be the previous, now outdated value when the focusout event appears. A workaround is to set the debounce time in case of focusout to 0: `data-ng-model-options="{ updateOn: 'default focusout', debounce: { 'default': 300, 'focusout': 0 } }"`.
It would be great if this could somehow be checked automatically by ax-input to achieve a predictable behavior.

**Comment by x1B** [comment]
_Closing invalid:_ I opened a new issue at LaxarJS/ax-input-control#6
